r2/config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'index',to:'simple_pages#index'
  root 'simple_pages#landing_page'
  resources :simple_pages
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

r2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

r2/app/models/order.rb
class Order<ApplicationRecord
  belongs_to:product
end

r2/app/models/product.rb
class Product < ApplicationRecord
end

r2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

r2/app/controllers/orders_controller.rb
class OrdersController<ApplicationController
  def index
    @orders=Order.includes(:product).all
  end

  def show
    @order=Order.find(params[:id])
  end

  def new
  end

  def create
  end

  def destroy
  end

end

r2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour,:price)
    end
end

r2/app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end
  def landing_page
    @products=Product.limit(3)
  end
end

r2/app/helpers/application_helper.rb
module ApplicationHelper
end

r2/app/helpers/products_helper.rb
module ProductsHelper
end

r2/app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

r2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R2</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
  </head>

  <body>
    <nav>
      <ul class="nav nav-tabs">
         <%= link_to "Home",root_path,class:"nav-link active" %>
          <%= link_to "About",simple_pages_about_path,class:"nav-link active" %>
          <%= link_to "Contact",simple_pages_contact_path,class:"nav-link active" %>
      </ul>
    </nav>

  <%= yield %>

  </<footer>
    &copy; 2018 Bike Berlin
  </footer>

  </body>
</html>

r2/app/views/orders/index.html.erb
<div class="row">
  <% @orders.each do |order| %>
   <div class="col-sm">
     <h1>Order # <%= order.id %> </h1>
     <%= link_to order.product.name, order %>
     <p><%= order.product.description %></p>
     <strong>$ <%= order.product.price %></strong>
   </div>
   <% end %>
 </div>

r2/app/views/orders/show.html.erb
<div class="container" >
  <h2> Order Information </h2>
   <strong> Order ID: </strong><%= @order.id %>
   <strong> Product Name: </strong><%= @order.product.name %>
   <strong> Product Price: </strong><%= number_to_currency(@order.product.price/100.to_f) %>
   <strong> Total Price: </strong><%= number_to_currency(@order.total/100.to_f) %>
 </div>

r2/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

r2/app/views/products/_products.html.erb
<%= render partial: "product", collection: @products %>

r2/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

r2/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>


    <div class="container-fluid">
     <div class="row">
     <% @products.each do |product| %>
     <div class="col-sm">
       <a href="#"><h1><%= product.name %></h1></a>
       <%= image_tag(product.image_url, class: "img-fluid") unless product.image_url.nil? %>
       <p><%= product.description %></p>
       <p><%= product.colour %></p>
       <strong><%= product.price %></strong>
       </div>
       <% end %>
       </div>
       </div>


<br>

<%= @test_variable %>

<%= link_to 'New Product', new_product_path %>

r2/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

r2/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

r2/app/views/simple_pages/about.html.erb
<h1>About US</h1>

<head>
<style>
.well {
  margin: auto;
  width: 60%;
  border: 3px solid #73AD21;
  padding: 10px;
}
</style>
</head>


		  <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
			<div class="well">

        <%= image_tag("racebikes.jpg",class: "img-responsive my-image") %>

				<p class="">This is a project regarding stationery items that can be utilized for various
        purposes.</p>
			</div>
			<p>
        Stationary items include pens,pencils and other such equipment.
			</p>
		  </div>
	</div>
</div>

r2/app/views/simple_pages/contact.html.erb
<head>
<style>
</style>
</head>
<header>
	<h1>Contact us</h1>
</header>
<body>
<section id="cover">
    <div id="cover-caption">
        <div id="container" class="container">
            <div class="row text-white">
                <div class="col-sm-6 offset-sm-3 text-center">
                    <h1 class="display-4"> Contact Us </h1>
                    <div class="info-form">
                        <form action="" class="form-inlin justify-content-center">
                            <div class="form-group">
                                <label class="sr-only">Name</label>
                                <input type="text" class="form-control" placeholder="Jane Doe">
                            </div>
                            <div class="form-group">
                                <label class="sr-only">Email</label>
                                <input type="text" class="form-control" placeholder="jane.doe@example.com">
                            </div>
                            <button type="submit" class="btn btn-success ">Login</button>
                        </form>
                    </div>
                    <br>

                </div>
            </div>
        </div>
    </div>
</section>
</body>
</div>

r2/app/views/simple_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>
<p>Welcome! The date and time is <%= Time.now %></p>



<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
  <hr>

<%= image_tag("racebike.jpg",class: "img-responsive my-image") %>

  <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
</div>





<footer class="site-footer">
  I'm the Sticky Footer.
</footer>

r2/app/views/simple_pages/landing_page.html.erb
<h2>Featured Product: </h2>
<%# @featured_product.name %>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    <% @products.each do |product| %>
    <div class="carousel-item <%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url, class: "d-block w-100") %>
      <div class="carousel-caption d-none d-md-block">
        <h3><%= product.name %></h3>
      </div>
    </div>
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  <%# <!--  <div class="carousel-item">
      <div class="carousel-item">
        <img src="..." alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>...</h5>
          <p>...</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="carousel-item">
        <img src="..." alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>...</h5>
          <p>...</p>
        </div>
      </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> %>